# Generated by Django 4.2.5 on 2023-11-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_schedule_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('calendar', 'name')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='owner',
        ),
    ]
