# Generated by Django 4.2.6 on 2023-11-20 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_schedule_unique_together_remove_schedule_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecalendar',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_cal', to=settings.AUTH_USER_MODEL),
        ),
    ]
