# Generated by Django 4.2.6 on 2023-11-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_schedulecalendar_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='value',
            field=models.IntegerField(choices=[(1, 'Main'), (2, 'Alt1'), (3, 'Alt2')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('calendar', 'name', 'value')},
        ),
    ]
