# Generated by Django 4.2.6 on 2023-12-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_schedule_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='calendar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='testing.schedulecalendar'),
        ),
    ]
