# Generated by Django 4.2.6 on 2023-11-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_schedule_unique_together_schedule_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='calendar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_schedule', to='testing.schedulecalendar'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='value',
            field=models.IntegerField(blank=True, choices=[(1, 'Main'), (2, 'Alt1'), (3, 'Alt2')], default=1),
        ),
    ]
