# Generated by Django 4.2.6 on 2023-12-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_schedule_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['name', 'value']},
        ),
    ]
