# Generated by Django 4.2.6 on 2023-12-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_alter_schedulecalendar_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulecalendar',
            unique_together=set(),
        ),
    ]
