# Generated by Django 4.2.6 on 2023-12-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_alter_schedulecalendar_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulecalendar',
            unique_together={('owner', 'name')},
        ),
    ]
