# Generated by Django 4.2.6 on 2024-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_alter_schedulecalendar_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
