# Generated by Django 5.0.1 on 2024-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_dailyevent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyevent',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailyevent',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
